server:
  port: 8081
spring:
  application:
    name: product
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/productm
    username: root
    password: KM@852147154
#### ---work config---
#  datasource:
#    url: jdbc:mysql://localhost:3306/productm
#    username: root
#    password: 123456

