server:
  port: 8097
spring:
  application:
    name: notification
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/productm
    username: root
    password: KM@852147154