server:
  port: 8085
spring:
  application:
    name: discount
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/discountm
    username: root
    password: KM@852147154
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true


